name: Build Game for Multiple Platforms
on: [push, workflow_dispatch]

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: casiland
  PROJECT_PATH: .

concurrency: 
  cancel-in-progress: true
  group: build-dev
jobs:
  export-multiplatform:
    name: Windows Export
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows, linux, web, mac]
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Perform ${{matrix.os}} build
        run: |
          mkdir -v -p build/${{matrix.os}}
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "${{matrix.os}}" "$EXPORT_DIR/${{matrix.os}}/$EXPORT_NAME.exe"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.os}}
          path: build/${{matrix.os}}
      
      - name: Install rsync 📚
        if: matrix.os == 'web'
        run: |
          apt-get update && apt-get install -y rsync
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        if: matrix.os == 'web'
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/web # The folder the action should deploy.
  
  deploy_releases:
    name: Deploy Releases
    runs-on: ubuntu-latest
    needs: [export-multiplatform]
    permissions: 
      contents: 
        write
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
      - name: Display structure of downloaded files
        run: ls -R        
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Dev Build
          tag_name: dev
          files: |
            windows.zip
            linux.zip
            mac.zip
            web.zip

      
