name: Sync with gitlab
on: push
concurrency: 
  cancel-in-progress: true
  group: sync-with-gitlab
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Push To Gitlab
        run: |
          echo Starting to push repo to gitlab
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin "https://oauth2:${{secrets.GITLAB_TOKEN}}@gitlab.com/prpkng/casiland-godot.git"
          git fetch
          git push --all --force origin
